apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uivio-ingress
  labels:
    app.kubernetes.io/name: uivio-ingress
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api/sandbox"
        backend:
          service:
            name: sandbox-service
            port: 
              number: 80
